login:
    path: /
    controller: App\Controller\LoginController::mostrarLogin


stockp:
    path: /stockp
    controller: App\Controller\StockController::mostrarStock
    
princ:
    path: /princ
    controller: App\Controller\GestionController::listarCategorias    

registro:
    path: /registro
    controller: App\Controller\RegistroController::mostrarRegistro

agregar:
    path: /agregar
    controller: App\Controller\AgregarController::mostrarAgregar

usuario:
    path: /usuario
    controller: App\Controller\UsuarioController::mostrarUsuario

informacion:
    path: /informacion
    controller: App\Controller\InformacionController::mostrarPerfiles